name: Auto merge Codex pull requests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge-codex:
    if: startsWith(github.head_ref, 'codex/')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-auto-merge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
